/// Canonical Bible book identification.
///
/// Translations key their data by localized book names ("Genesis",
/// "ኦሪት ዘፍጥረት", "I Samuel", "1 Samuel"…). To keep the reader on the same
/// book when switching translations — including NT-only or Apocrypha-bearing
/// ones where positional indexes disagree — book names are resolved to
/// OSIS-style canonical IDs and matched by ID.
library;

/// Resolves a translation's book name/key to a canonical ID (e.g. 'GEN',
/// '1SA', 'MAT'). Returns null when the name is not recognized (e.g. a
/// translation in a language without aliases yet); callers should fall back
/// to positional mapping.
String? resolveBookId(String name) => _aliases[_normalize(name)];

/// Canonical IDs of the 27 New Testament books, in canonical order.
const Set<String> newTestamentIds = {
  'MAT',
  'MRK',
  'LUK',
  'JHN',
  'ACT',
  'ROM',
  '1CO',
  '2CO',
  'GAL',
  'EPH',
  'PHP',
  'COL',
  '1TH',
  '2TH',
  '1TI',
  '2TI',
  'TIT',
  'PHM',
  'HEB',
  'JAS',
  '1PE',
  '2PE',
  '1JN',
  '2JN',
  '3JN',
  'JUD',
  'REV',
};

/// True when the name resolves to a New Testament book, false when it
/// resolves to an Old Testament or deuterocanonical one, null when the
/// name is not recognized.
bool? isNewTestamentBook(String name) {
  final id = resolveBookId(name);
  if (id == null) return null;
  return newTestamentIds.contains(id);
}

String _normalize(String name) {
  var s = name.trim().toLowerCase();
  // Strip Ethiopic full stop and Latin punctuation.
  s = s.replaceAll(RegExp(r'[።\.\,\:\;]'), '');
  s = s.replaceAll(RegExp(r'\s+'), ' ').trim();
  // Leading roman numerals / ordinals -> digits: "i samuel" -> "1 samuel".
  s = s.replaceFirstMapped(
    RegExp(r'^(iii|ii|i|1st|2nd|3rd|first|second|third)\s'),
    (m) => switch (m[1]) {
      'i' || '1st' || 'first' => '1 ',
      'ii' || '2nd' || 'second' => '2 ',
      _ => '3 ',
    },
  );
  if (s.startsWith('the ')) s = s.substring(4);
  return s;
}

/// The 66-book Protestant canon in order, with chapter counts.
/// Used to generate reading plans and to iterate books canonically.
const List<(String, int)> canonicalBooks = [
  ('GEN', 50),
  ('EXO', 40),
  ('LEV', 27),
  ('NUM', 36),
  ('DEU', 34),
  ('JOS', 24),
  ('JDG', 21),
  ('RUT', 4),
  ('1SA', 31),
  ('2SA', 24),
  ('1KI', 22),
  ('2KI', 25),
  ('1CH', 29),
  ('2CH', 36),
  ('EZR', 10),
  ('NEH', 13),
  ('EST', 10),
  ('JOB', 42),
  ('PSA', 150),
  ('PRO', 31),
  ('ECC', 12),
  ('SNG', 8),
  ('ISA', 66),
  ('JER', 52),
  ('LAM', 5),
  ('EZK', 48),
  ('DAN', 12),
  ('HOS', 14),
  ('JOL', 3),
  ('AMO', 9),
  ('OBA', 1),
  ('JON', 4),
  ('MIC', 7),
  ('NAM', 3),
  ('HAB', 3),
  ('ZEP', 3),
  ('HAG', 2),
  ('ZEC', 14),
  ('MAL', 4),
  ('MAT', 28),
  ('MRK', 16),
  ('LUK', 24),
  ('JHN', 21),
  ('ACT', 28),
  ('ROM', 16),
  ('1CO', 16),
  ('2CO', 13),
  ('GAL', 6),
  ('EPH', 6),
  ('PHP', 4),
  ('COL', 4),
  ('1TH', 5),
  ('2TH', 3),
  ('1TI', 6),
  ('2TI', 4),
  ('TIT', 3),
  ('PHM', 1),
  ('HEB', 13),
  ('JAS', 5),
  ('1PE', 5),
  ('2PE', 3),
  ('1JN', 5),
  ('2JN', 1),
  ('3JN', 1),
  ('JUD', 1),
  ('REV', 22),
];

/// English display names for canonical IDs — the fallback when the current
/// translation doesn't contain a book (e.g. plan readings while an NT-only
/// translation is active).
const Map<String, String> bookDisplayNames = {
  'GEN': 'Genesis',
  'EXO': 'Exodus',
  'LEV': 'Leviticus',
  'NUM': 'Numbers',
  'DEU': 'Deuteronomy',
  'JOS': 'Joshua',
  'JDG': 'Judges',
  'RUT': 'Ruth',
  '1SA': '1 Samuel',
  '2SA': '2 Samuel',
  '1KI': '1 Kings',
  '2KI': '2 Kings',
  '1CH': '1 Chronicles',
  '2CH': '2 Chronicles',
  'EZR': 'Ezra',
  'NEH': 'Nehemiah',
  'EST': 'Esther',
  'JOB': 'Job',
  'PSA': 'Psalms',
  'PRO': 'Proverbs',
  'ECC': 'Ecclesiastes',
  'SNG': 'Song of Solomon',
  'ISA': 'Isaiah',
  'JER': 'Jeremiah',
  'LAM': 'Lamentations',
  'EZK': 'Ezekiel',
  'DAN': 'Daniel',
  'HOS': 'Hosea',
  'JOL': 'Joel',
  'AMO': 'Amos',
  'OBA': 'Obadiah',
  'JON': 'Jonah',
  'MIC': 'Micah',
  'NAM': 'Nahum',
  'HAB': 'Habakkuk',
  'ZEP': 'Zephaniah',
  'HAG': 'Haggai',
  'ZEC': 'Zechariah',
  'MAL': 'Malachi',
  'MAT': 'Matthew',
  'MRK': 'Mark',
  'LUK': 'Luke',
  'JHN': 'John',
  'ACT': 'Acts',
  'ROM': 'Romans',
  '1CO': '1 Corinthians',
  '2CO': '2 Corinthians',
  'GAL': 'Galatians',
  'EPH': 'Ephesians',
  'PHP': 'Philippians',
  'COL': 'Colossians',
  '1TH': '1 Thessalonians',
  '2TH': '2 Thessalonians',
  '1TI': '1 Timothy',
  '2TI': '2 Timothy',
  'TIT': 'Titus',
  'PHM': 'Philemon',
  'HEB': 'Hebrews',
  'JAS': 'James',
  '1PE': '1 Peter',
  '2PE': '2 Peter',
  '1JN': '1 John',
  '2JN': '2 John',
  '3JN': '3 John',
  'JUD': 'Jude',
  'REV': 'Revelation',
};

const Map<String, String> _aliases = {
  // --- Old Testament (English) ---
  'genesis': 'GEN',
  'exodus': 'EXO',
  'leviticus': 'LEV',
  'numbers': 'NUM',
  'deuteronomy': 'DEU',
  'joshua': 'JOS',
  'judges': 'JDG',
  'ruth': 'RUT',
  '1 samuel': '1SA',
  '2 samuel': '2SA',
  '1 kings': '1KI',
  '2 kings': '2KI',
  '1 chronicles': '1CH',
  '2 chronicles': '2CH',
  'ezra': 'EZR',
  'nehemiah': 'NEH',
  'esther': 'EST',
  'job': 'JOB',
  'psalms': 'PSA',
  'psalm': 'PSA',
  'proverbs': 'PRO',
  'ecclesiastes': 'ECC',
  'song of solomon': 'SNG',
  'song of songs': 'SNG',
  'canticles': 'SNG',
  'isaiah': 'ISA',
  'jeremiah': 'JER',
  'lamentations': 'LAM',
  'ezekiel': 'EZK',
  'daniel': 'DAN',
  'hosea': 'HOS',
  'joel': 'JOL',
  'amos': 'AMO',
  'obadiah': 'OBA',
  'jonah': 'JON',
  'micah': 'MIC',
  'nahum': 'NAM',
  'habakkuk': 'HAB',
  'zephaniah': 'ZEP',
  'haggai': 'HAG',
  'zechariah': 'ZEC',
  'malachi': 'MAL',
  // --- Deuterocanon / Apocrypha (English, KJVA naming) ---
  '1 esdras': '1ES',
  '2 esdras': '2ES',
  'tobit': 'TOB',
  'judith': 'JDT',
  'additions to esther': 'ESG',
  'wisdom': 'WIS',
  'wisdom of solomon': 'WIS',
  'sirach': 'SIR',
  'ecclesiasticus': 'SIR',
  'baruch': 'BAR',
  'prayer of azariah': 'S3Y',
  'susanna': 'SUS',
  'bel and the dragon': 'BEL',
  'prayer of manasses': 'MAN',
  'prayer of manasseh': 'MAN',
  '1 maccabees': '1MA',
  '2 maccabees': '2MA',
  // --- New Testament (English) ---
  'matthew': 'MAT',
  'gospel according to saint matthew': 'MAT',
  'mark': 'MRK',
  'gospel according to saint mark': 'MRK',
  'luke': 'LUK',
  'gospel according to saint luke': 'LUK',
  'john': 'JHN',
  'gospel according to saint john': 'JHN',
  'acts': 'ACT',
  'acts of the apostles': 'ACT',
  'romans': 'ROM',
  '1 corinthians': '1CO',
  '2 corinthians': '2CO',
  'galatians': 'GAL',
  'ephesians': 'EPH',
  'philippians': 'PHP',
  'colossians': 'COL',
  '1 thessalonians': '1TH',
  '2 thessalonians': '2TH',
  '1 timothy': '1TI',
  '2 timothy': '2TI',
  'titus': 'TIT',
  'philemon': 'PHM',
  'hebrews': 'HEB',
  'james': 'JAS',
  '1 peter': '1PE',
  '2 peter': '2PE',
  '1 john': '1JN',
  '2 john': '2JN',
  '3 john': '3JN',
  'jude': 'JUD',
  'revelation': 'REV',
  'revelation of john': 'REV',
  'apocalypse': 'REV',
  // --- Old Testament (Amharic 1954) ---
  'ኦሪት ዘፍጥረት': 'GEN',
  'ኦሪት ዘጸአት': 'EXO',
  'ኦሪት ዘሌዋውያን': 'LEV',
  'ኦሪት ዘኍልቍ': 'NUM',
  'ኦሪት ዘዳግም': 'DEU',
  'መጽሐፈ ኢያሱ ወልደ ነዌ': 'JOS',
  'መጽሐፈ መሣፍንት': 'JDG',
  'መጽሐፈ ሩት': 'RUT',
  'መጽሐፈ ሳሙኤል ቀዳማዊ': '1SA',
  'መጽሐፈ ሳሙኤል ካል': '2SA', // truncated "ካልዕ" as shipped in the data
  'መጽሐፈ ሳሙኤል ካልዕ': '2SA',
  'መጽሐፈ ነገሥት ቀዳማዊ': '1KI',
  'መጽሐፈ ነገሥት ካልዕ': '2KI',
  'መጽሐፈ ዜና መዋዕል ቀዳማዊ': '1CH',
  'መጽሐፈ ዜና መዋዕል ካልዕ': '2CH',
  'መጽሐፈ ዕዝራ': 'EZR',
  'መጽሐፈ ነህምያ': 'NEH',
  'መጽሐፈ አስቴር': 'EST',
  'መጽሐፈ ኢዮብ': 'JOB',
  'መዝሙረ ዳዊት': 'PSA',
  'መጽሐፈ ምሳሌ': 'PRO',
  'መጽሐፈ መክብብ': 'ECC',
  'መኃልየ መኃልይ ዘሰሎሞን': 'SNG',
  'ትንቢተ ኢሳይያስ': 'ISA',
  'ትንቢተ ኤርምያስ': 'JER',
  'ሰቆቃው ኤርምያስ': 'LAM',
  'ትንቢተ ሕዝቅኤል': 'EZK',
  'ትንቢተ ዳንኤል': 'DAN',
  'ትንቢተ ሆሴዕ': 'HOS',
  'ትንቢተ ኢዮኤል': 'JOL',
  'ትንቢተ አሞጽ': 'AMO',
  'ትንቢተ አብድዩ': 'OBA',
  'ትንቢተ ዮናስ': 'JON',
  'ትንቢተ ሚክያስ': 'MIC',
  'ትንቢተ ናሆም': 'NAM',
  'ትንቢተ ዕንባቆም': 'HAB',
  'ትንቢተ ሶፎንያስ': 'ZEP',
  'ትንቢተ ሐጌ': 'HAG',
  'ትንቢተ ዘካርያስ': 'ZEC',
  'ትንቢተ ሚልክያ': 'MAL',
  // --- New Testament (Amharic 1954) ---
  'የማቴዎስ ወንጌል': 'MAT',
  'የማርቆስ ወንጌል': 'MRK',
  'የሉቃስ ወንጌል': 'LUK',
  'የዮሐንስ ወንጌል': 'JHN',
  'የሐዋርያት ሥራ': 'ACT',
  'ወደ ሮሜ ሰዎች': 'ROM',
  '1ኛ ወደ ቆሮንቶስ ሰዎች': '1CO',
  '2ኛ ወደ ቆሮንቶስ ሰዎች': '2CO',
  'ወደ ገላትያ ሰዎች': 'GAL',
  'ወደ ኤፌሶን ሰዎች': 'EPH',
  'ወደ ፊልጵስዩስ ሰዎች': 'PHP',
  'ወደ ቆላስይስ ሰዎች': 'COL',
  '1ኛ ወደ ተሰሎንቄ ሰዎች': '1TH',
  '2ኛ ወደ ተሰሎንቄ ሰዎች': '2TH',
  '1ኛ ወደ ጢሞቴዎስ': '1TI',
  '2ኛ ወደ ጢሞቴዎስ': '2TI',
  'ወደ ቲቶ': 'TIT',
  'ወደ ፊልሞና': 'PHM',
  'ወደ ዕብራውያን': 'HEB',
  'የያዕቆብ መልእክት': 'JAS',
  '1ኛ የጴጥሮስ መልእክት': '1PE',
  '2ኛ የጴጥሮስ መልእክት': '2PE',
  '1ኛ የዮሐንስ መልእክት': '1JN',
  '2ኛ የዮሐንስ መልእክት': '2JN',
  '3ኛ የዮሐንስ መልእክት': '3JN',
  'የይሁዳ መልእክት': 'JUD',
  'የዮሐንስ ራእይ': 'REV',
};
